### ISSUE TITLE
1.0 TODO

### ISSUE THREAD

**Issue by dy** [dfcreative/regl-scatter2d#1]
* [x] ~~Multipass rendering with sorted colors~~ too slow generally
* [x] ~~[point-cluster](https://github.com/dfcreative/point-cluster) snap-point-2d-based, but eventually quad-tree-based~~ separate concern
* [x] ~~SDF rendering~~ superceded by sprite
* [x] ~~gl-plot2d integration (all gl-scatter2d tests)~~ refactored to integrate to plotly directly
* [ ] ~~selected points~~
* [ ] ~~GPU-less picking - add tests~~
* [x] ~~scatter-lasso commit~~
* [x] add/test precision option
* [ ] ~~add demo with settings-panel~~
* [x] make sure glyph sizes are normalized to indicated size, prob use optical-properties for alignment
* [x] make sure glyph border size is normalized too
* [x] 1e6 points test: add snapping audio-option
* [x] ~~test out depth test, prob avoiding markers of the same depth lvl~~ no serious perf gain
* [x] detect color palette in a better way by clustering colors
* [x] test 1e6 points against gl-scatter2d (demo pages)
* [x] ~~use snap-points oct tree for hover detection~~
* [x] ~~put unnormalized points to GPU~~ no significant boost (18ms for 1e6 pts)

**Comment by dy** [comment]
Oct-tree is fixed by #11
